### ISSUE TITLE
CLS_extractor.py

### ISSUE THREAD

**Issue by Wangxq7** [SonalKumar95/DatUS#2]
Hello, 

when I was executing the code, I met the problem of undefined target. Under the premise that viz_validSegs is False, how to understand the target here? Thank you in advance for your reply!

**Comment by SonalKumar95** [comment]
Thanks for pointing out the bug. The "target' is the path to the folder to store the valid segments for visualization. I have updated the code (CLS_extractor.py) accordingly and changed the default value of 'viz_validSegs' to 'True.' Visualizing the segment can be helpful in deciding the minimum number of patches for the valid segments (may be different for different datasets). Set 'viz_validSegs' to 'False' if you don't want to visualize the valid segment. Storing segments of a large dataset may require extra storage.
